[project]
name = "yolo-blur-py"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "argparse>=1.4.0",
    "numpy>=2.1.2",
    "onnxruntime>=1.19.2",
    "opencv-python>=4.10.0.84",
    "structlog>=24.4.0",
    "tqdm>=4.67.0",
]
